AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - './db/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'Gemfile'

Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 12

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
